# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.github_token }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');
      - name: Echo
        run: echo ${{ steps.tag.outputs.result }}

      - name: Branch name
        id: branch_name
        run: |
                echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
                echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
                echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Build base image
        run: |
                echo $SOURCE_NAME
                echo $SOURCE_BRANCH
                echo $SOURCE_TAG
        env:
                SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
                SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
                SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}

      - name: Check if version has been updated
        id: version_check
        uses: EndBug/version-check@v1
        with:
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: echo Extract branch name
        run: |
                echo ${{ steps.version_check.outputs.changed }}
                echo ${{ steps.version_check.outputs.type }}
                echo ${{ steps.version_check.outputs.commit }}
                echo ${{ steps.version_check.outputs.version }}
                echo ${{ steps.extract_branch.outputs.branch }}

        
      - name: echo Extract branch name
        if: steps.version_check.outputs.changed == 'true' && steps.extract_branch.outputs.branch == 'main'
        run: |
                echo ${{ steps.version_check.outputs.changed }}
                echo ${{ steps.version_check.outputs.type }}
                echo ${{ steps.version_check.outputs.commit }}
                echo ${{ steps.version_check.outputs.version }}
                echo ${{ steps.extract_branch.outputs.branch }}

