# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKENN }}
      - uses: yanamura/ios-bump-version@v1
        with:
          version: 1.1.0
      - name: update
        run: |
          git add .
          git commit -m "bump version"
          git push origin HEAD
        
      - name: "#️⃣ Generate Build Number"
        id: buildnumber
        uses: einaregilsson/build-number@v2
        with:
          token: ${{ secrets.github_token }}

      - name: echo build number
        run: echo Hello, world!  ${{ steps.buildnumber.outputs.build_number }}

      - name: Generate build number
        id: buildnumber_My
        uses: einaregilsson/build-number@v3 
        with:
          token: ${{ secrets.github_token }}
          prefix: client
      - name: echo build number
        run: echo Hello, world!  ${{ steps.buildnumber_My.outputs.build_number }}





      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
